# Generated by Django 6.0.3 on 2026-03-16 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='user_files/%Y/%m/%d/')),
                ('name', models.CharField(blank=True, help_text='文件名称（可选）', max_length=255)),
                ('description', models.TextField(blank=True, help_text='文件描述（可选）')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_type', models.CharField(blank=True, help_text='文件类型', max_length=50)),
                ('size', models.BigIntegerField(blank=True, help_text='文件大小（字节）', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
