# Generated by Django 5.2.13 on 2026-05-08 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='景点名称')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL标识')),
                ('city', models.CharField(max_length=100, verbose_name='所在城市')),
                ('province', models.CharField(max_length=100, verbose_name='所在省份')),
                ('country', models.CharField(default='中国', max_length=100, verbose_name='国家')),
                ('category', models.CharField(choices=[('nature', '自然风光'), ('culture', '人文历史'), ('food', '美食购物'), ('leisure', '休闲娱乐'), ('outdoor', '户外探险')], max_length=50, verbose_name='分类')),
                ('description', models.TextField(verbose_name='景点介绍')),
                ('image', models.ImageField(blank=True, null=True, upload_to='destination_images/', verbose_name='景点图片')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='纬度')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='经度')),
                ('rating', models.FloatField(default=0, verbose_name='评分')),
                ('visit_count', models.PositiveIntegerField(default=0, verbose_name='访问热度')),
                ('best_season', models.CharField(default='全年', max_length=100, verbose_name='最佳季节')),
                ('recommended_days', models.PositiveIntegerField(default=1, verbose_name='建议游玩天数')),
                ('ticket_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='门票价格')),
                ('opening_hours', models.CharField(default='全天', max_length=200, verbose_name='开放时间')),
                ('tips', models.TextField(blank=True, verbose_name='旅游贴士')),
                ('is_featured', models.BooleanField(default=False, verbose_name='精选推荐')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='TripDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField(verbose_name='第几天')),
                ('date', models.DateField(verbose_name='日期')),
                ('notes', models.TextField(blank=True, verbose_name='当天备注')),
            ],
            options={
                'ordering': ['day_number'],
            },
        ),
        migrations.CreateModel(
            name='TripDayItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='活动名称')),
                ('description', models.TextField(blank=True, verbose_name='活动描述')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='结束时间')),
                ('transportation', models.CharField(choices=[('walk', '步行'), ('bus', '公交'), ('metro', '地铁'), ('taxi', '打车'), ('drive', '自驾')], default='walk', max_length=50, verbose_name='交通方式')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='day_items', to='travel.destination', verbose_name='关联景点')),
                ('trip_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='travel.tripday', verbose_name='所属天')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TripPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='计划标题')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL标识')),
                ('description', models.TextField(blank=True, verbose_name='计划描述')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('budget_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='总预算')),
                ('preferences', models.CharField(blank=True, max_length=200, verbose_name='旅行偏好')),
                ('status', models.CharField(choices=[('planning', '规划中'), ('ongoing', '进行中'), ('completed', '已完成')], default='planning', max_length=20, verbose_name='状态')),
                ('is_public', models.BooleanField(default=False, verbose_name='公开分享')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_plans', to='travel.destination', verbose_name='主要目的地')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_plans', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
        ),
        migrations.AddField(
            model_name='tripday',
            name='trip_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='travel.tripplan', verbose_name='所属计划'),
        ),
        migrations.CreateModel(
            name='TravelNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL标识')),
                ('content', models.TextField(verbose_name='正文')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='travel_notes/', verbose_name='封面图')),
                ('is_published', models.BooleanField(default=False, verbose_name='已发布')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_notes', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('trip_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='travel.tripplan', verbose_name='关联旅行计划')),
            ],
        ),
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('transport', '交通'), ('accommodation', '住宿'), ('dining', '餐饮'), ('tickets', '门票'), ('shopping', '购物'), ('other', '其他')], max_length=50, verbose_name='类别')),
                ('planned_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='预算金额')),
                ('actual_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='实际花费')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('trip_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_items', to='travel.tripplan', verbose_name='所属计划')),
            ],
        ),
    ]
